/* -- WPPA+ Runtime parameters
/*
/* Dynamicly Created on 2018-04-19T15:37:09+00:00
/*
*/

	/* Check if wppa.js and jQuery are present */
	if (typeof(_wppaSlides) == 'undefined') alert('There is a problem with your theme. The file wppa.js is not loaded when it is expected (Errloc = wppa_kickoff).');
	if (typeof(jQuery) == 'undefined') alert('There is a problem with your theme. The jQuery library is not loaded when it is expected (Errloc = wppa_kickoff).');

	wppaVersion = "6-8-00-012";
	wppaDebug = false;
	wppaBackgroundColorImage = "#eeeeee";
	wppaPopupLinkType = "photo";
	wppaAnimationType = "fadeover";
	wppaAnimationSpeed = 800;
	wppaThumbnailAreaDelta = 14;
	wppaTextFrameDelta = 181;
	wppaBoxDelta = 14;
	wppaSlideShowTimeOut = 2500;
	wppaFilmShowGlue = true;
	wppaSlideShow = "Slideshow";
	wppaStart = "Start";
	wppaStop = "Stop";
	wppaSlower = "Slower";
	wppaFaster = "Faster";
	wppaPhoto = "Photo";
	wppaOf = "of";
	wppaPreviousPhoto = "Previous photo";
	wppaNextPhoto = "Next photo";
	wppaPrevP = "Prev.";
	wppaNextP = "Next";
	wppaAvgRating = "Average&nbsp;rating";
	wppaMyRating = "My&nbsp;rating";
	wppaAvgRat = "Avg.";
	wppaMyRat = "Mine";
	wppaDislikeMsg = "You marked this image as inappropriate.";
	wppaMiniTreshold = 500;
	wppaRatingOnce = false;
	wppaPleaseName = "Please enter your name";
	wppaPleaseEmail = "Please enter a valid email address";
	wppaPleaseComment = "Please enter a comment";
	wppaHideWhenEmpty = false;
	wppaBGcolorNumbar = "#cccccc";
	wppaBcolorNumbar = "#cccccc";
	wppaBGcolorNumbarActive = "#333333";
	wppaBcolorNumbarActive = "#333333";
	wppaFontFamilyNumbar = "";
	wppaFontSizeNumbar = "px";
	wppaFontColorNumbar = "#777777";
	wppaFontWeightNumbar = "normal";
	wppaFontFamilyNumbarActive = "";
	wppaFontSizeNumbarActive = "px";
	wppaFontColorNumbarActive = "#777777";
	wppaFontWeightNumbarActive = "bold";
	wppaNumbarMax = "10";
	wppaLang = "en";
	wppaNextOnCallback = false;
	wppaStarOpacity = 0.2;
	wppaEmailRequired = "required";
	wppaSlideBorderWidth = 0;
	wppaAllowAjax = true;
	wppaUsePhotoNamesInUrls = false;
	wppaThumbTargetBlank = false;
	wppaRatingMax = 5;
	wppaRatingDisplayType = "graphic";
	wppaRatingPrec = 2;
	wppaStretch = false;
	wppaMinThumbSpace = 4;
	wppaThumbSpaceAuto = true;
	wppaMagnifierCursor = "magnifier-small.png";
	wppaArtMonkyLink = "none";
	wppaAutoOpenComments = true;
	wppaUpdateAddressLine = true;
	wppaFilmThumbTitle = "Double click to start/stop slideshow running";
	wppaClickToView = "Click to view";
	wppaVoteForMe = "Vote for me!";
	wppaVotedForMe = "Voted for me";
	wppaSlideSwipe = false;
	wppaMaxCoverWidth = 1024;
	wppaDownLoad = "Download";
	wppaSlideToFullpopup = false;
	wppaComAltSize = 75;
	wppaBumpViewCount = true;
	wppaBumpClickCount = false;
	wppaShareHideWhenRunning = true;
	wppaFotomoto = false;
	wppaArtMonkeyButton = true;
	wppaFotomotoHideWhenRunning = false;
	wppaCommentRequiredAfterVote = false;
	wppaFotomotoMinWidth = 400;
	wppaShortQargs = true;
	wppaOvlHires = false;
	wppaSlideVideoStart = false;
	wppaSlideAudioStart = false;
	wppaRel = "data-rel";
	wppaOvlRadius = 12;
	wppaOvlBorderWidth = 8;
	wppaEditPhotoWidth = "960";
	wppaThemeStyles = "";
	wppaStickyHeaderHeight = 0;
	wppaRenderModal = false;
	wppaModalQuitImg = "url(http://podoba.ua/wp-content/plugins/wp-photo-album-plus/img/smallcross-black.gif)";
	wppaBoxRadius = "6";
	wppaModalBgColor = "#ffffff";
	wppaUploadEdit = "-none-";
	wppaSvgFillcolor = "#666666";
	wppaSvgBgcolor = "transparent";
	wppaOvlSvgFillcolor = "#999999";
	wppaOvlSvgBgcolor = "transparent";
	wppaSvgCornerStyle = "medium";
	